export { AboutSection } from "./AboutSection"
export { ContactSection } from "./ContactSection"
export { HeroSection } from "./HeroSection"
export { SchemeSection } from "./SchemeSection"
export { ServicesSection } from "./ServicesSection"
